# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveMarket' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveMarket
  pod 'AlamofireObjectMapper', '~> 3.0’
  pod 'SwiftEventBus', '~> 1.1.0'
  pod 'PureLayout'

  target 'LiveMarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveMarketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
